steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "filter-branch"
    env: ['TARGET_BRANCH=master']
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$BRANCH_NAME" == "$$TARGET_BRANCH" ]]; then \
          true \
        else \
          echo 'Processing was skipped because the branch is not '"$$TARGET_BRANCH"'. Although "ERROR" is output, there is no problem.'; \
          exit 1; \
        fi

  - name: "gcr.io/cloud-builders/docker"
    id: "build-php56"
    waitFor: "filter-branch"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
        --pull \
        --build-arg ENV=gke \
        -t "gcr.io/$PROJECT_ID/$REPO_NAME/php:$COMMIT_SHA" \
        -t "gcr.io/$PROJECT_ID/$REPO_NAME/php:latest" \
        -f "Dockerfile" \
        .
    dir: "5.6/alpine3.8/apache-cli"

images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME/php:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/$REPO_NAME/php:latest"
