steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-php56"
    args:
      - "build"
      - "--pull"
      - "--build-arg"
      - "ENV=gke"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME/forsurvey:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME/forsurvey:$COMMIT_SHA"
      - "-f"
      - "Dockerfile"
      - "."
    dir: "5.6/alpine3.8/apache-cli"

images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME/php:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/$REPO_NAME/php:latest"
