steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-php56"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
        --pull \
        --build-arg ENV=gke \
        -t "gcr.io/$PROJECT_ID/$REPO_NAME/php:$COMMIT_SHA" \
        -t "gcr.io/$PROJECT_ID/$REPO_NAME/php:latest" \
        -f "Dockerfile" .
    dir: "5.6/alpine3.8/apache-cli"

images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME/php:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/$REPO_NAME/php:latest"

substitutions:
  _TARGET_BRANCH: master
